import type { User } from "@/types/user";

const userData: User[] = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2023-10-01 10:00:00",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-09-28 14:30:00",
  },
  {
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2023-10-02 08:15:00",
  },
  {
    name: "Bob Williams",
    email: "bob.williams@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-10-03 11:45:00",
  },
  {
    name: "Carol Davis",
    email: "carol.davis@example.com",
    role: "Moderator",
    status: "Active",
    lastLogin: "2023-10-01 16:20:00",
  },
  {
    name: "David Martinez",
    email: "david.martinez@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-09-15 09:00:00",
  },
  {
    name: "Eva Thompson",
    email: "eva.thompson@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2023-10-04 13:30:00",
  },
  {
    name: "Frank Garcia",
    email: "frank.garcia@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2023-10-04 07:55:00",
  },
  {
    name: "Grace Lee",
    email: "grace.lee@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-10-03 17:10:00",
  },
  {
    name: "Henry Wilson",
    email: "henry.wilson@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-08-30 12:00:00",
  },
  {
    name: "Iris Brown",
    email: "iris.brown@example.com",
    role: "Moderator",
    status: "Active",
    lastLogin: "2023-10-02 15:45:00",
  },
  {
    name: "Jack Taylor",
    email: "jack.taylor@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-10-01 10:30:00",
  },
  {
    name: "Karen Anderson",
    email: "karen.anderson@example.com",
    role: "Editor",
    status: "Inactive",
    lastLogin: "2023-09-20 11:00:00",
  },
  {
    name: "Leo Thomas",
    email: "leo.thomas@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-10-04 09:25:00",
  },
  {
    name: "Mia Jackson",
    email: "mia.jackson@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-10-03 14:00:00",
  },
  {
    name: "Nathan White",
    email: "nathan.white@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2023-10-04 08:40:00",
  },
  {
    name: "Olivia Harris",
    email: "olivia.harris@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-09-10 16:50:00",
  },
  {
    name: "Paul Clark",
    email: "paul.clark@example.com",
    role: "Moderator",
    status: "Active",
    lastLogin: "2023-10-02 10:15:00",
  },
  {
    name: "Quinn Lewis",
    email: "quinn.lewis@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2023-10-03 12:55:00",
  },
  {
    name: "Rachel Robinson",
    email: "rachel.robinson@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-09-25 18:00:00",
  },
];

export default userData;
